import type { Metadata } from "next";
import { Source_Sans_3, Poppins } from "next/font/google";
import "./globals.css";

const source_sans = Source_Sans_3({
  variable: "--source-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  fallback: ["Arial", "sans-serif"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${source_sans.variable} antialiased bg-base-100 transition-all duration-300 ease-in-out`}
      >
        {children}
      </body>
    </html>
  );
}
