export {default as GitHub} from './GitHub.svg';
export {default as LinkedIn} from './LinkedIn.svg';
export {default as Instagram} from './Instagram.svg';
export {default as ChevronDown} from './ChevronDown.svg';
export {default as ThemeIcon} from './ThemeIcon.svg';
export {default as Hero} from './Hero.svg';
export {default as Circle} from './Circle.svg';
export {default as RoadmapPath} from './RoadmapPath.svg';
export {default as Download} from './Download.svg';
export {default as React} from './React.svg';
export {default as TypeScript} from './TypeScript.svg';
// export {default as NextJS} from './NextJS.svg';
export {default as TailwindCSS} from './TailwindCSS.svg';
export {default as NodeJS} from './NodeJS.svg';
export {default as Docker} from './Docker.svg';
export {default as Figma} from './Figma.svg';
// export {default as Vercel} from './Vercel.svg';
export {default as SEO} from './SEO.svg';
export {default as SCSS} from './SCSS.svg';
export {default as LanguageIcon} from './LanguageIcon.svg';